{
 "title": "ND064-COURSE4",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Up Time (Percentage)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\n  (\n    sum without() (up{container=~\"backend|frontend|trial\"})\n      or\n    (0 * sum_over_time(up{container=~\"backend|frontend|trial\"}[30d]))\n  )[30d:5m]\n) and\nsum_over_time(up{container=~\"backend|frontend|trial\"}[1h])",
     "legendFormat": "{{pod}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Replicas/Container",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{deployment=~\"frontend|backend|trial\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Jaeger Traces (By Service)",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(jaeger:traces_total) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "4xx & 5xx Responses (Per Second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{status=~\"4..|5..\"}[$__rate_interval])) by (endpoint, path, status)",
     "legendFormat": "{{endpoint}}{{path}} - {{status}}"
    }
   ]
  },
  {
   "title": "Total Requests (Per Second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{container=~\"backend|trial|frontend\"}[$__rate_interval])) by (container, path)",
     "legendFormat": "{{container}}{{path}}"
    }
   ]
  },
  {
   "title": "Jaeger Recent Traces (Backend Service)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "limit": 5, "service": "nd064course4-backend-service" }
   ]
  },
  {
   "title": "Jaeger Recent Traces (Trial Service)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "limit": 5, "service": "nd064course4-trial-service" }
   ]
  },
  {
   "title": "Error Response Rate (Per Second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (sum(rate(flask_http_request_duration_seconds_count{status=~\"2.*|4.*\"}[$__rate_interval])))/(sum(rate(flask_http_request_duration_seconds_count[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Success Reponses Rate (Per Second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(rate(flask_http_request_duration_seconds_count{status=~\"2.*|4.*\"}[$__rate_interval])))/(sum(rate(flask_http_request_duration_seconds_count[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Response Times (99th Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (container, path, le) (rate(flask_http_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "{{container}}{{path}}"
    }
   ]
  },
  {
   "title": "Response Times (95th Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (container, path, le) (rate(flask_http_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "{{container}}{{path}}"
    }
   ]
  },
  {
   "title": "Response Times (Median)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (container, path, le) (rate(flask_http_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "{{container}}{{path}}"
    }
   ]
  },
  {
   "title": "Response Times (Average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_sum[$__rate_interval])/rate(flask_http_request_duration_seconds_count[$__rate_interval])) by (endpoint, path)",
     "legendFormat": "{{endpoint}}{{path}}"
    }
   ]
  },
  {
   "title": "CPU Usage (By Pod)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=~\"frontend|backend|trial\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage (By Pod)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container=~\"frontend|backend|trial\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Utilization (By Node)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "instance:node_cpu_utilisation:rate5m",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Utilization (By Node)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "instance:node_memory_utilisation:ratio",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}